alias sudo="sudo "
alias cls="clear"
test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
alias ls="ls --color=auto --time-style=long-iso"
alias l="ls -CF --group-directories-first"
alias la="ls -CFA --group-directories-first"
alias ll="ls -CFl --group-directories-first"
alias lla="ls -CFlA --group-directories-first"
