[[plugins]]
repo = "vim-denops/denops.vim"
rev  = "886bfa038d75d415677f8a7a62e8940c74554707"
frozen = true
[[plugins]]
repo = "Shougo/dpp.vim"
rev  = "456c8f80cb763d32c77f87399e53b37adddee460"
frozen = true
[[plugins]]
repo = "Shougo/dpp-ext-lazy"
rev  = "b19a52bbb6e35dec2c681423b0709cd41f38eb2b"
frozen = true
[[plugins]]
repo = "Shougo/dpp-ext-toml"
rev  = "3e2390478eb194e24487fa2de225596135f94749"
frozen = true
[[plugins]]
repo = "Shougo/dpp-ext-installer"
rev  = "ac522815ee9cd2cb62c21c453dd1e54e35fde1fa"
frozen = true
[[plugins]]
repo = "Shougo/dpp-protocol-git"
rev  = "582159dda8579f8d954d6e689d57ffbceaeaf17d"
frozen = true

[[plugins]]
repo = "kaarmu/typst.vim"
