[[plugins]]
repo = "tomasr/molokai"
on_event = "VimEnter"
lua_post_source = """vim.cmd.colorscheme("molokai")"""

# ddc.vim
[[plugins]]
repo = "Shougo/ddc.vim"
on_event = "VimEnter"
depends = [
	"denops.vim",
	"pum.vim",
	"ddc-ui-pum",
	"ddc-source-vim-lsp",
	"ddc-filter-matcher_head",
	"ddc-filter-sorter_rank",
]
lua_post_source = """
	vim.fn['ddc#custom#patch_global']('ui', 'pum')
	vim.fn['ddc#custom#patch_global']('sources', { 'vim-lsp' })
	vim.fn['ddc#custom#patch_global']('sourceOptions', {
		['vim-lsp'] = {
			matchers = { 'matcher_head' },
			sorters = { 'sorter_rank' },
			forceCompletionPattern= [[\\.\\w*|:\\w*|->\\w*]]
		}
	})
	vim.fn['ddc#enable']()
"""

# ddc.vim ui
[[plugins]]
repo = "Shougo/pum.vim"
on_source = "ddc.vim"
lua_post_source = """
	vim.keymap.set('i', '<Tab>',   function() if vim.fn['pum#visible']() == true then vim.call('pum#map#select_relative',  1)     else return '<Tab>'   end end, { expr = true })
	vim.keymap.set('i', '<S-Tab>', function() if vim.fn['pum#visible']() == true then vim.call('pum#map#select_relative', -1)     else return '<S-Tab>' end end, { expr = true })
	vim.keymap.set('i', '<Esc>',   function() if vim.fn['pum#visible']() == true then vim.call('pum#map#cancel')                  else return '<Esc>'   end end, { expr = true })
	vim.keymap.set('i', '<Up>',    function() if vim.fn['pum#visible']() == true then vim.call('pum#map#cancel') return '<Up>'    else return '<Up>'    end end, { expr = true })
	vim.keymap.set('i', '<Down>',  function() if vim.fn['pum#visible']() == true then vim.call('pum#map#cancel') return '<Down>'  else return '<Down>'  end end, { expr = true })
	vim.keymap.set('i', '<Left>',  function() if vim.fn['pum#visible']() == true then vim.call('pum#map#cancel') return '<Left>'  else return '<Left>'  end end, { expr = true })
	vim.keymap.set('i', '<Right>', function() if vim.fn['pum#visible']() == true then vim.call('pum#map#cancel') return '<Right>' else return '<Right>' end end, { expr = true })
	vim.keymap.set('i', '<CR>',    function() if vim.fn['pum#visible']() == true then vim.call('pum#map#confirm')                 else return '<CR>'    end end, { expr = true })
"""
[[plugins]]
repo = "Shougo/ddc-ui-pum"
on_source = "ddc.vim"
depends = ["denops.vim", "pum.vim"]

# ddc.vim source
[[plugins]]
repo = "prabirshrestha/vim-lsp"
[[plugins]]
repo = "mattn/vim-lsp-settings"
depends = ["vim-lsp"]
[[plugins]]
repo = "shun/ddc-source-vim-lsp"
depends = ["denops.vim", "vim-lsp-settings", "vim-lsp"]

# ddc.vim filter
[[plugins]]
repo = "Shougo/ddc-filter-matcher_head"
depends = ["denops.vim"]
[[plugins]]
repo = "Shougo/ddc-filter-sorter_rank"
depends = ["denops.vim"]

[[plugins]]
repo = "rust-lang/rust.vim"
ft = "rust"
lua_post_source = """
	vim.g['rustfmt_autosave'] = 0
	vim.g['rustfmt_fail_silently'] = 1
	vim.keymap.set('n', '==', vim.cmd['RustFmt'])
	vim.keymap.set('n', '<F5>', vim.cmd['RustRun'])
	vim.keymap.set('n', '<F12>', vim.cmd['RustTest'])
"""
